# Site settings
title: Discountry
logo: book.png
email: feibilanceon@gmail.com
description: Discountry's DEV Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://discountry.github.io" # the base hostname & protocol for your site
imageurl: "https://discountry.github.io/images/"
twitter_username: discountifu
github_username:  discountry

# Build settings
excerpt_separator: <!--more-->
permalink: pretty
markdown: kramdown
highlighter: rouge

#Pagination
paginate: 6

